# Book settings
title: Introducción al método de Monte Carlo y a MCMC
author: Pablo Huijse Heise 
#logo: logo.png
only_build_toc_files: true
#exclude_patterns : [_build, "**.ipynb_checkpoints"]

execute:
  execute_notebooks: cache
  allow_errors: true
  timeout: 360

repository:
  url: https://github.com/phuijse/INFO274

html:
  home_page_in_navbar: false
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: false
  only_build_toc_files: true

sphinx:
  extra_extensions: [bokeh.sphinxext.bokeh_plot]
  config:
    html_show_copyright: false
    language: es
    myst_enable_extensions: 
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

latex:
  latex_documents:
    targetname: book.tex
