title: Introducción al método de Monte Carlo y a MCMC
author: Pablo Huijse Heise 
copyright: "2021"
logo: logo.png
only_build_toc_files: true

execute:
  execute_notebooks: 'off'

repository:
  url: https://github.com/phuijse/INFO274

html:
  home_page_in_navbar: false
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: false
  only_build_toc_files: true

sphinx:
  extra_extensions: 
    - sphinx_proof
  config:
    language: es
    myst_enable_extensions: 
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution


